// <auto-generated />
using System;
using JobPortal_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPortal_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519091622_TiposContratos")]
    partial class TiposContratos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JobPortal_API.Models.AplicacaoTrabalho", b =>
                {
                    b.Property<int>("IdAplicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAplicacao"), 1L, 1);

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCandidato")
                        .HasColumnType("int");

                    b.Property<int?>("IdOferta")
                        .HasColumnType("int");

                    b.Property<string>("aplicacaoAceite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAplicacao");

                    b.HasIndex("IdCandidato");

                    b.HasIndex("IdOferta");

                    b.ToTable("AplicacaoTrabalho");
                });

            modelBuilder.Entity("JobPortal_API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("JobPortal_API.Models.Candidato", b =>
                {
                    b.Property<int>("IdCandidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCandidato"), 1L, 1);

                    b.Property<DateTime?>("DataNasc")
                        .HasColumnType("Date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Telefone")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCandidato");

                    b.HasIndex("UserId");

                    b.ToTable("Candidato");
                });

            modelBuilder.Entity("JobPortal_API.Models.Concelho", b =>
                {
                    b.Property<int>("IdConcelho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConcelho"), 1L, 1);

                    b.Property<string>("NomeConcelho")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdConcelho");

                    b.ToTable("Concelho");

                    b.HasData(
                        new
                        {
                            IdConcelho = 1,
                            NomeConcelho = "Abrantes"
                        },
                        new
                        {
                            IdConcelho = 2,
                            NomeConcelho = "Aguiar da Beira"
                        },
                        new
                        {
                            IdConcelho = 3,
                            NomeConcelho = "Alandroal"
                        },
                        new
                        {
                            IdConcelho = 4,
                            NomeConcelho = "Albergaria-a-Velha"
                        },
                        new
                        {
                            IdConcelho = 5,
                            NomeConcelho = "Albufeira"
                        },
                        new
                        {
                            IdConcelho = 6,
                            NomeConcelho = "Alcanena"
                        },
                        new
                        {
                            IdConcelho = 7,
                            NomeConcelho = "Alcobaça"
                        },
                        new
                        {
                            IdConcelho = 8,
                            NomeConcelho = "Alcochete"
                        },
                        new
                        {
                            IdConcelho = 9,
                            NomeConcelho = "Alcoutim"
                        },
                        new
                        {
                            IdConcelho = 10,
                            NomeConcelho = "Alcácer do Sal"
                        },
                        new
                        {
                            IdConcelho = 11,
                            NomeConcelho = "Alenquer"
                        },
                        new
                        {
                            IdConcelho = 12,
                            NomeConcelho = "Alfândega da Fé"
                        },
                        new
                        {
                            IdConcelho = 13,
                            NomeConcelho = "Alijó"
                        },
                        new
                        {
                            IdConcelho = 14,
                            NomeConcelho = "Aljezur"
                        },
                        new
                        {
                            IdConcelho = 15,
                            NomeConcelho = "Aljustrel"
                        },
                        new
                        {
                            IdConcelho = 16,
                            NomeConcelho = "Almada"
                        },
                        new
                        {
                            IdConcelho = 17,
                            NomeConcelho = "Almeida"
                        },
                        new
                        {
                            IdConcelho = 18,
                            NomeConcelho = "Almeirim"
                        },
                        new
                        {
                            IdConcelho = 19,
                            NomeConcelho = "Almodôvar"
                        },
                        new
                        {
                            IdConcelho = 20,
                            NomeConcelho = "Alpiarça"
                        },
                        new
                        {
                            IdConcelho = 21,
                            NomeConcelho = "Alter do Chão"
                        },
                        new
                        {
                            IdConcelho = 22,
                            NomeConcelho = "Alvaiázere"
                        },
                        new
                        {
                            IdConcelho = 23,
                            NomeConcelho = "Alvito"
                        },
                        new
                        {
                            IdConcelho = 24,
                            NomeConcelho = "Amadora"
                        },
                        new
                        {
                            IdConcelho = 25,
                            NomeConcelho = "Amarante"
                        },
                        new
                        {
                            IdConcelho = 26,
                            NomeConcelho = "Amares"
                        },
                        new
                        {
                            IdConcelho = 27,
                            NomeConcelho = "Anadia"
                        },
                        new
                        {
                            IdConcelho = 28,
                            NomeConcelho = "Angra do Heroísmo"
                        },
                        new
                        {
                            IdConcelho = 29,
                            NomeConcelho = "Ansião"
                        },
                        new
                        {
                            IdConcelho = 30,
                            NomeConcelho = "Arcos de Valdevez"
                        },
                        new
                        {
                            IdConcelho = 31,
                            NomeConcelho = "Arganil"
                        },
                        new
                        {
                            IdConcelho = 32,
                            NomeConcelho = "Armamar"
                        },
                        new
                        {
                            IdConcelho = 33,
                            NomeConcelho = "Arouca"
                        },
                        new
                        {
                            IdConcelho = 34,
                            NomeConcelho = "Arraiolos"
                        },
                        new
                        {
                            IdConcelho = 35,
                            NomeConcelho = "Arronches"
                        },
                        new
                        {
                            IdConcelho = 36,
                            NomeConcelho = "Arruda dos Vinhos"
                        },
                        new
                        {
                            IdConcelho = 37,
                            NomeConcelho = "Aveiro"
                        },
                        new
                        {
                            IdConcelho = 38,
                            NomeConcelho = "Avis"
                        },
                        new
                        {
                            IdConcelho = 39,
                            NomeConcelho = "Azambuja"
                        },
                        new
                        {
                            IdConcelho = 40,
                            NomeConcelho = "Baião"
                        },
                        new
                        {
                            IdConcelho = 41,
                            NomeConcelho = "Barcelos"
                        },
                        new
                        {
                            IdConcelho = 42,
                            NomeConcelho = "Barrancos"
                        },
                        new
                        {
                            IdConcelho = 43,
                            NomeConcelho = "Barreiro"
                        },
                        new
                        {
                            IdConcelho = 44,
                            NomeConcelho = "Batalha"
                        },
                        new
                        {
                            IdConcelho = 45,
                            NomeConcelho = "Beja"
                        },
                        new
                        {
                            IdConcelho = 46,
                            NomeConcelho = "Belmonte"
                        },
                        new
                        {
                            IdConcelho = 47,
                            NomeConcelho = "Benavente"
                        },
                        new
                        {
                            IdConcelho = 48,
                            NomeConcelho = "Bombarral"
                        },
                        new
                        {
                            IdConcelho = 49,
                            NomeConcelho = "Borba"
                        },
                        new
                        {
                            IdConcelho = 50,
                            NomeConcelho = "Boticas"
                        },
                        new
                        {
                            IdConcelho = 51,
                            NomeConcelho = "Braga"
                        },
                        new
                        {
                            IdConcelho = 52,
                            NomeConcelho = "Bragança"
                        },
                        new
                        {
                            IdConcelho = 53,
                            NomeConcelho = "Cabeceiras de Basto"
                        },
                        new
                        {
                            IdConcelho = 54,
                            NomeConcelho = "Cadaval"
                        },
                        new
                        {
                            IdConcelho = 55,
                            NomeConcelho = "Caldas da Rainha"
                        },
                        new
                        {
                            IdConcelho = 56,
                            NomeConcelho = "Calheta "
                        },
                        new
                        {
                            IdConcelho = 57,
                            NomeConcelho = "Caminha"
                        },
                        new
                        {
                            IdConcelho = 58,
                            NomeConcelho = "Campo Maior"
                        },
                        new
                        {
                            IdConcelho = 59,
                            NomeConcelho = "Cantanhede"
                        },
                        new
                        {
                            IdConcelho = 60,
                            NomeConcelho = "Carrazeda de Ansiães"
                        },
                        new
                        {
                            IdConcelho = 61,
                            NomeConcelho = "Carregal do Sal"
                        },
                        new
                        {
                            IdConcelho = 62,
                            NomeConcelho = "Cartaxo"
                        },
                        new
                        {
                            IdConcelho = 63,
                            NomeConcelho = "Cascais"
                        },
                        new
                        {
                            IdConcelho = 64,
                            NomeConcelho = "Castanheira de Pêra"
                        },
                        new
                        {
                            IdConcelho = 65,
                            NomeConcelho = "Castelo Branco"
                        },
                        new
                        {
                            IdConcelho = 66,
                            NomeConcelho = "Castelo de Paiva"
                        },
                        new
                        {
                            IdConcelho = 67,
                            NomeConcelho = "Castelo de Vide"
                        },
                        new
                        {
                            IdConcelho = 68,
                            NomeConcelho = "Castro Daire"
                        },
                        new
                        {
                            IdConcelho = 69,
                            NomeConcelho = "Castro Marim"
                        },
                        new
                        {
                            IdConcelho = 70,
                            NomeConcelho = "Castro Verde"
                        },
                        new
                        {
                            IdConcelho = 71,
                            NomeConcelho = "Celorico da Beira"
                        },
                        new
                        {
                            IdConcelho = 72,
                            NomeConcelho = "Celorico de Basto"
                        },
                        new
                        {
                            IdConcelho = 73,
                            NomeConcelho = "Chamusca"
                        },
                        new
                        {
                            IdConcelho = 74,
                            NomeConcelho = "Chaves"
                        },
                        new
                        {
                            IdConcelho = 75,
                            NomeConcelho = "Cinfães"
                        },
                        new
                        {
                            IdConcelho = 76,
                            NomeConcelho = "Coimbra"
                        },
                        new
                        {
                            IdConcelho = 77,
                            NomeConcelho = "Condeixa-a-Nova"
                        },
                        new
                        {
                            IdConcelho = 78,
                            NomeConcelho = "Constância"
                        },
                        new
                        {
                            IdConcelho = 79,
                            NomeConcelho = "Coruche"
                        },
                        new
                        {
                            IdConcelho = 80,
                            NomeConcelho = "Corvo"
                        },
                        new
                        {
                            IdConcelho = 81,
                            NomeConcelho = "Covilhã"
                        },
                        new
                        {
                            IdConcelho = 82,
                            NomeConcelho = "Crato"
                        },
                        new
                        {
                            IdConcelho = 83,
                            NomeConcelho = "Cuba"
                        },
                        new
                        {
                            IdConcelho = 84,
                            NomeConcelho = "Câmara de Lobos"
                        },
                        new
                        {
                            IdConcelho = 85,
                            NomeConcelho = "Elvas"
                        },
                        new
                        {
                            IdConcelho = 86,
                            NomeConcelho = "Entroncamento"
                        },
                        new
                        {
                            IdConcelho = 87,
                            NomeConcelho = "Espinho"
                        },
                        new
                        {
                            IdConcelho = 88,
                            NomeConcelho = "Esposende"
                        },
                        new
                        {
                            IdConcelho = 89,
                            NomeConcelho = "Estarreja"
                        },
                        new
                        {
                            IdConcelho = 90,
                            NomeConcelho = "Estremoz"
                        },
                        new
                        {
                            IdConcelho = 91,
                            NomeConcelho = "Fafe"
                        },
                        new
                        {
                            IdConcelho = 92,
                            NomeConcelho = "Faro"
                        },
                        new
                        {
                            IdConcelho = 93,
                            NomeConcelho = "Felgueiras"
                        },
                        new
                        {
                            IdConcelho = 94,
                            NomeConcelho = "Ferreira do Alentejo"
                        },
                        new
                        {
                            IdConcelho = 95,
                            NomeConcelho = "Ferreira do Zêzere"
                        },
                        new
                        {
                            IdConcelho = 96,
                            NomeConcelho = "Figueira da Foz"
                        },
                        new
                        {
                            IdConcelho = 97,
                            NomeConcelho = "Figueira de Castelo Rodrigo"
                        },
                        new
                        {
                            IdConcelho = 98,
                            NomeConcelho = "Figueiró dos Vinhos"
                        },
                        new
                        {
                            IdConcelho = 99,
                            NomeConcelho = "Fornos de Algodres"
                        },
                        new
                        {
                            IdConcelho = 100,
                            NomeConcelho = "Freixo de Espada à Cinta"
                        },
                        new
                        {
                            IdConcelho = 101,
                            NomeConcelho = "Fronteira"
                        },
                        new
                        {
                            IdConcelho = 102,
                            NomeConcelho = "Funchal"
                        },
                        new
                        {
                            IdConcelho = 103,
                            NomeConcelho = "Fundão"
                        },
                        new
                        {
                            IdConcelho = 104,
                            NomeConcelho = "Gavião"
                        },
                        new
                        {
                            IdConcelho = 105,
                            NomeConcelho = "Golegã"
                        },
                        new
                        {
                            IdConcelho = 106,
                            NomeConcelho = "Gondomar"
                        },
                        new
                        {
                            IdConcelho = 107,
                            NomeConcelho = "Gouveia"
                        },
                        new
                        {
                            IdConcelho = 108,
                            NomeConcelho = "Grândola"
                        },
                        new
                        {
                            IdConcelho = 109,
                            NomeConcelho = "Guarda"
                        },
                        new
                        {
                            IdConcelho = 110,
                            NomeConcelho = "Guimarães"
                        },
                        new
                        {
                            IdConcelho = 111,
                            NomeConcelho = "Góis"
                        },
                        new
                        {
                            IdConcelho = 112,
                            NomeConcelho = "Horta"
                        },
                        new
                        {
                            IdConcelho = 113,
                            NomeConcelho = "Idanha-a-Nova"
                        },
                        new
                        {
                            IdConcelho = 114,
                            NomeConcelho = "Lagoa "
                        },
                        new
                        {
                            IdConcelho = 115,
                            NomeConcelho = "Lagos"
                        },
                        new
                        {
                            IdConcelho = 116,
                            NomeConcelho = "Lajes das Flores"
                        },
                        new
                        {
                            IdConcelho = 117,
                            NomeConcelho = "Lajes do Pico"
                        },
                        new
                        {
                            IdConcelho = 118,
                            NomeConcelho = "Lamego"
                        },
                        new
                        {
                            IdConcelho = 119,
                            NomeConcelho = "Leiria"
                        },
                        new
                        {
                            IdConcelho = 120,
                            NomeConcelho = "Lisboa"
                        },
                        new
                        {
                            IdConcelho = 121,
                            NomeConcelho = "Loulé"
                        },
                        new
                        {
                            IdConcelho = 122,
                            NomeConcelho = "Loures"
                        },
                        new
                        {
                            IdConcelho = 123,
                            NomeConcelho = "Lourinhã"
                        },
                        new
                        {
                            IdConcelho = 124,
                            NomeConcelho = "Lousada"
                        },
                        new
                        {
                            IdConcelho = 125,
                            NomeConcelho = "Lousã"
                        },
                        new
                        {
                            IdConcelho = 126,
                            NomeConcelho = "Macedo de Cavaleiros"
                        },
                        new
                        {
                            IdConcelho = 127,
                            NomeConcelho = "Machico"
                        },
                        new
                        {
                            IdConcelho = 128,
                            NomeConcelho = "Madalena"
                        },
                        new
                        {
                            IdConcelho = 129,
                            NomeConcelho = "Mafra"
                        },
                        new
                        {
                            IdConcelho = 130,
                            NomeConcelho = "Maia"
                        },
                        new
                        {
                            IdConcelho = 131,
                            NomeConcelho = "Mangualde"
                        },
                        new
                        {
                            IdConcelho = 132,
                            NomeConcelho = "Manteigas"
                        },
                        new
                        {
                            IdConcelho = 133,
                            NomeConcelho = "Marco de Canaveses"
                        },
                        new
                        {
                            IdConcelho = 134,
                            NomeConcelho = "Marinha Grande"
                        },
                        new
                        {
                            IdConcelho = 135,
                            NomeConcelho = "Marvão"
                        },
                        new
                        {
                            IdConcelho = 136,
                            NomeConcelho = "Matosinhos"
                        },
                        new
                        {
                            IdConcelho = 137,
                            NomeConcelho = "Mação"
                        },
                        new
                        {
                            IdConcelho = 138,
                            NomeConcelho = "Mealhada"
                        },
                        new
                        {
                            IdConcelho = 139,
                            NomeConcelho = "Meda"
                        },
                        new
                        {
                            IdConcelho = 140,
                            NomeConcelho = "Melgaço"
                        },
                        new
                        {
                            IdConcelho = 141,
                            NomeConcelho = "Mesão Frio"
                        },
                        new
                        {
                            IdConcelho = 142,
                            NomeConcelho = "Mira"
                        },
                        new
                        {
                            IdConcelho = 143,
                            NomeConcelho = "Miranda do Corvo"
                        },
                        new
                        {
                            IdConcelho = 144,
                            NomeConcelho = "Miranda do Douro"
                        },
                        new
                        {
                            IdConcelho = 145,
                            NomeConcelho = "Mirandela"
                        },
                        new
                        {
                            IdConcelho = 146,
                            NomeConcelho = "Mogadouro"
                        },
                        new
                        {
                            IdConcelho = 147,
                            NomeConcelho = "Moimenta da Beira"
                        },
                        new
                        {
                            IdConcelho = 148,
                            NomeConcelho = "Moita"
                        },
                        new
                        {
                            IdConcelho = 149,
                            NomeConcelho = "Monchique"
                        },
                        new
                        {
                            IdConcelho = 150,
                            NomeConcelho = "Mondim de Basto"
                        },
                        new
                        {
                            IdConcelho = 151,
                            NomeConcelho = "Monforte"
                        },
                        new
                        {
                            IdConcelho = 152,
                            NomeConcelho = "Montalegre"
                        },
                        new
                        {
                            IdConcelho = 153,
                            NomeConcelho = "Montemor-o-Novo"
                        },
                        new
                        {
                            IdConcelho = 154,
                            NomeConcelho = "Montemor-o-Velho"
                        },
                        new
                        {
                            IdConcelho = 155,
                            NomeConcelho = "Montijo"
                        },
                        new
                        {
                            IdConcelho = 156,
                            NomeConcelho = "Monção"
                        },
                        new
                        {
                            IdConcelho = 157,
                            NomeConcelho = "Mora"
                        },
                        new
                        {
                            IdConcelho = 158,
                            NomeConcelho = "Mortágua"
                        },
                        new
                        {
                            IdConcelho = 159,
                            NomeConcelho = "Moura"
                        },
                        new
                        {
                            IdConcelho = 160,
                            NomeConcelho = "Mourão"
                        },
                        new
                        {
                            IdConcelho = 161,
                            NomeConcelho = "Murtosa"
                        },
                        new
                        {
                            IdConcelho = 162,
                            NomeConcelho = "Murça"
                        },
                        new
                        {
                            IdConcelho = 163,
                            NomeConcelho = "Mértola"
                        },
                        new
                        {
                            IdConcelho = 164,
                            NomeConcelho = "Nazaré"
                        },
                        new
                        {
                            IdConcelho = 165,
                            NomeConcelho = "Nelas"
                        },
                        new
                        {
                            IdConcelho = 166,
                            NomeConcelho = "Nisa"
                        },
                        new
                        {
                            IdConcelho = 167,
                            NomeConcelho = "Nordeste"
                        },
                        new
                        {
                            IdConcelho = 168,
                            NomeConcelho = "Odemira"
                        },
                        new
                        {
                            IdConcelho = 169,
                            NomeConcelho = "Odivelas"
                        },
                        new
                        {
                            IdConcelho = 170,
                            NomeConcelho = "Oeiras"
                        },
                        new
                        {
                            IdConcelho = 171,
                            NomeConcelho = "Oleiros"
                        },
                        new
                        {
                            IdConcelho = 172,
                            NomeConcelho = "Olhão"
                        },
                        new
                        {
                            IdConcelho = 173,
                            NomeConcelho = "Oliveira de Azeméis"
                        },
                        new
                        {
                            IdConcelho = 174,
                            NomeConcelho = "Oliveira de Frades"
                        },
                        new
                        {
                            IdConcelho = 175,
                            NomeConcelho = "Oliveira do Bairro"
                        },
                        new
                        {
                            IdConcelho = 176,
                            NomeConcelho = "Oliveira do Hospital"
                        },
                        new
                        {
                            IdConcelho = 177,
                            NomeConcelho = "Ourique"
                        },
                        new
                        {
                            IdConcelho = 178,
                            NomeConcelho = "Ourém"
                        },
                        new
                        {
                            IdConcelho = 179,
                            NomeConcelho = "Ovar"
                        },
                        new
                        {
                            IdConcelho = 180,
                            NomeConcelho = "Palmela"
                        },
                        new
                        {
                            IdConcelho = 181,
                            NomeConcelho = "Pampilhosa da Serra"
                        },
                        new
                        {
                            IdConcelho = 182,
                            NomeConcelho = "Paredes"
                        },
                        new
                        {
                            IdConcelho = 183,
                            NomeConcelho = "Paredes de Coura"
                        },
                        new
                        {
                            IdConcelho = 184,
                            NomeConcelho = "Paços de Ferreira"
                        },
                        new
                        {
                            IdConcelho = 185,
                            NomeConcelho = "Pedrógão Grande"
                        },
                        new
                        {
                            IdConcelho = 186,
                            NomeConcelho = "Penacova"
                        },
                        new
                        {
                            IdConcelho = 187,
                            NomeConcelho = "Penafiel"
                        },
                        new
                        {
                            IdConcelho = 188,
                            NomeConcelho = "Penalva do Castelo"
                        },
                        new
                        {
                            IdConcelho = 189,
                            NomeConcelho = "Penamacor"
                        },
                        new
                        {
                            IdConcelho = 190,
                            NomeConcelho = "Penedono"
                        },
                        new
                        {
                            IdConcelho = 191,
                            NomeConcelho = "Penela"
                        },
                        new
                        {
                            IdConcelho = 192,
                            NomeConcelho = "Peniche"
                        },
                        new
                        {
                            IdConcelho = 193,
                            NomeConcelho = "Peso da Régua"
                        },
                        new
                        {
                            IdConcelho = 194,
                            NomeConcelho = "Pinhel"
                        },
                        new
                        {
                            IdConcelho = 195,
                            NomeConcelho = "Pombal"
                        },
                        new
                        {
                            IdConcelho = 196,
                            NomeConcelho = "Ponta Delgada"
                        },
                        new
                        {
                            IdConcelho = 197,
                            NomeConcelho = "Ponta do Sol"
                        },
                        new
                        {
                            IdConcelho = 198,
                            NomeConcelho = "Ponte da Barca"
                        },
                        new
                        {
                            IdConcelho = 199,
                            NomeConcelho = "Ponte de Lima"
                        },
                        new
                        {
                            IdConcelho = 200,
                            NomeConcelho = "Ponte de Sor"
                        },
                        new
                        {
                            IdConcelho = 201,
                            NomeConcelho = "Portalegre"
                        },
                        new
                        {
                            IdConcelho = 202,
                            NomeConcelho = "Portel"
                        },
                        new
                        {
                            IdConcelho = 203,
                            NomeConcelho = "Portimão"
                        },
                        new
                        {
                            IdConcelho = 204,
                            NomeConcelho = "Porto"
                        },
                        new
                        {
                            IdConcelho = 205,
                            NomeConcelho = "Porto Moniz"
                        },
                        new
                        {
                            IdConcelho = 206,
                            NomeConcelho = "Porto Santo"
                        },
                        new
                        {
                            IdConcelho = 207,
                            NomeConcelho = "Porto de Mós"
                        },
                        new
                        {
                            IdConcelho = 208,
                            NomeConcelho = "Povoação"
                        },
                        new
                        {
                            IdConcelho = 209,
                            NomeConcelho = "Praia da Vitória"
                        },
                        new
                        {
                            IdConcelho = 210,
                            NomeConcelho = "Proença-a-Nova"
                        },
                        new
                        {
                            IdConcelho = 211,
                            NomeConcelho = "Póvoa de Lanhoso"
                        },
                        new
                        {
                            IdConcelho = 212,
                            NomeConcelho = "Póvoa de Varzim"
                        },
                        new
                        {
                            IdConcelho = 213,
                            NomeConcelho = "Redondo"
                        },
                        new
                        {
                            IdConcelho = 214,
                            NomeConcelho = "Reguengos de Monsaraz"
                        },
                        new
                        {
                            IdConcelho = 215,
                            NomeConcelho = "Resende"
                        },
                        new
                        {
                            IdConcelho = 216,
                            NomeConcelho = "Ribeira Brava"
                        },
                        new
                        {
                            IdConcelho = 217,
                            NomeConcelho = "Ribeira Grande"
                        },
                        new
                        {
                            IdConcelho = 218,
                            NomeConcelho = "Ribeira de Pena"
                        },
                        new
                        {
                            IdConcelho = 219,
                            NomeConcelho = "Rio Maior"
                        },
                        new
                        {
                            IdConcelho = 220,
                            NomeConcelho = "Sabrosa"
                        },
                        new
                        {
                            IdConcelho = 221,
                            NomeConcelho = "Sabugal"
                        },
                        new
                        {
                            IdConcelho = 222,
                            NomeConcelho = "Salvaterra de Magos"
                        },
                        new
                        {
                            IdConcelho = 223,
                            NomeConcelho = "Santa Comba Dão"
                        },
                        new
                        {
                            IdConcelho = 224,
                            NomeConcelho = "Santa Cruz"
                        },
                        new
                        {
                            IdConcelho = 225,
                            NomeConcelho = "Santa Cruz da Graciosa"
                        },
                        new
                        {
                            IdConcelho = 226,
                            NomeConcelho = "Santa Cruz das Flores"
                        },
                        new
                        {
                            IdConcelho = 227,
                            NomeConcelho = "Santa Maria da Feira"
                        },
                        new
                        {
                            IdConcelho = 228,
                            NomeConcelho = "Santa Marta de Penaguião"
                        },
                        new
                        {
                            IdConcelho = 229,
                            NomeConcelho = "Santana"
                        },
                        new
                        {
                            IdConcelho = 230,
                            NomeConcelho = "Santarém"
                        },
                        new
                        {
                            IdConcelho = 231,
                            NomeConcelho = "Santiago do Cacém"
                        },
                        new
                        {
                            IdConcelho = 232,
                            NomeConcelho = "Santo Tirso"
                        },
                        new
                        {
                            IdConcelho = 233,
                            NomeConcelho = "Sardoal"
                        },
                        new
                        {
                            IdConcelho = 234,
                            NomeConcelho = "Seia"
                        },
                        new
                        {
                            IdConcelho = 235,
                            NomeConcelho = "Seixal"
                        },
                        new
                        {
                            IdConcelho = 236,
                            NomeConcelho = "Sernancelhe"
                        },
                        new
                        {
                            IdConcelho = 237,
                            NomeConcelho = "Serpa"
                        },
                        new
                        {
                            IdConcelho = 238,
                            NomeConcelho = "Sertã"
                        },
                        new
                        {
                            IdConcelho = 239,
                            NomeConcelho = "Sesimbra"
                        },
                        new
                        {
                            IdConcelho = 240,
                            NomeConcelho = "Setúbal"
                        },
                        new
                        {
                            IdConcelho = 241,
                            NomeConcelho = "Sever do Vouga"
                        },
                        new
                        {
                            IdConcelho = 242,
                            NomeConcelho = "Silves"
                        },
                        new
                        {
                            IdConcelho = 243,
                            NomeConcelho = "Sines"
                        },
                        new
                        {
                            IdConcelho = 244,
                            NomeConcelho = "Sintra"
                        },
                        new
                        {
                            IdConcelho = 245,
                            NomeConcelho = "Sobral de Monte Agraço"
                        },
                        new
                        {
                            IdConcelho = 246,
                            NomeConcelho = "Soure"
                        },
                        new
                        {
                            IdConcelho = 247,
                            NomeConcelho = "Sousel"
                        },
                        new
                        {
                            IdConcelho = 248,
                            NomeConcelho = "Sátão"
                        },
                        new
                        {
                            IdConcelho = 249,
                            NomeConcelho = "São Brás de Alportel"
                        },
                        new
                        {
                            IdConcelho = 250,
                            NomeConcelho = "São João da Madeira"
                        },
                        new
                        {
                            IdConcelho = 251,
                            NomeConcelho = "São João da Pesqueira"
                        },
                        new
                        {
                            IdConcelho = 252,
                            NomeConcelho = "São Pedro do Sul"
                        },
                        new
                        {
                            IdConcelho = 253,
                            NomeConcelho = "São Roque do Pico"
                        },
                        new
                        {
                            IdConcelho = 254,
                            NomeConcelho = "São Vicente"
                        },
                        new
                        {
                            IdConcelho = 255,
                            NomeConcelho = "Tabuaço"
                        },
                        new
                        {
                            IdConcelho = 256,
                            NomeConcelho = "Tarouca"
                        },
                        new
                        {
                            IdConcelho = 257,
                            NomeConcelho = "Tavira"
                        },
                        new
                        {
                            IdConcelho = 258,
                            NomeConcelho = "Terras de Bouro"
                        },
                        new
                        {
                            IdConcelho = 259,
                            NomeConcelho = "Tomar"
                        },
                        new
                        {
                            IdConcelho = 260,
                            NomeConcelho = "Tondela"
                        },
                        new
                        {
                            IdConcelho = 261,
                            NomeConcelho = "Torre de Moncorvo"
                        },
                        new
                        {
                            IdConcelho = 262,
                            NomeConcelho = "Torres Novas"
                        },
                        new
                        {
                            IdConcelho = 263,
                            NomeConcelho = "Torres Vedras"
                        },
                        new
                        {
                            IdConcelho = 264,
                            NomeConcelho = "Trancoso"
                        },
                        new
                        {
                            IdConcelho = 265,
                            NomeConcelho = "Trofa"
                        },
                        new
                        {
                            IdConcelho = 266,
                            NomeConcelho = "Tábua"
                        },
                        new
                        {
                            IdConcelho = 267,
                            NomeConcelho = "Vagos"
                        },
                        new
                        {
                            IdConcelho = 268,
                            NomeConcelho = "Vale de Cambra"
                        },
                        new
                        {
                            IdConcelho = 269,
                            NomeConcelho = "Valença"
                        },
                        new
                        {
                            IdConcelho = 270,
                            NomeConcelho = "Valongo"
                        },
                        new
                        {
                            IdConcelho = 271,
                            NomeConcelho = "Valpaços"
                        },
                        new
                        {
                            IdConcelho = 272,
                            NomeConcelho = "Velas"
                        },
                        new
                        {
                            IdConcelho = 273,
                            NomeConcelho = "Vendas Novas"
                        },
                        new
                        {
                            IdConcelho = 274,
                            NomeConcelho = "Viana do Alentejo"
                        },
                        new
                        {
                            IdConcelho = 275,
                            NomeConcelho = "Viana do Castelo"
                        },
                        new
                        {
                            IdConcelho = 276,
                            NomeConcelho = "Vidigueira"
                        },
                        new
                        {
                            IdConcelho = 277,
                            NomeConcelho = "Vieira do Minho"
                        },
                        new
                        {
                            IdConcelho = 278,
                            NomeConcelho = "Vila Flor"
                        },
                        new
                        {
                            IdConcelho = 279,
                            NomeConcelho = "Vila Franca de Xira"
                        },
                        new
                        {
                            IdConcelho = 280,
                            NomeConcelho = "Vila Franca do Campo"
                        },
                        new
                        {
                            IdConcelho = 281,
                            NomeConcelho = "Vila Nova da Barquinha"
                        },
                        new
                        {
                            IdConcelho = 282,
                            NomeConcelho = "Vila Nova de Cerveira"
                        },
                        new
                        {
                            IdConcelho = 283,
                            NomeConcelho = "Vila Nova de Famalicão"
                        },
                        new
                        {
                            IdConcelho = 284,
                            NomeConcelho = "Vila Nova de Foz Côa"
                        },
                        new
                        {
                            IdConcelho = 285,
                            NomeConcelho = "Vila Nova de Gaia"
                        },
                        new
                        {
                            IdConcelho = 286,
                            NomeConcelho = "Vila Nova de Paiva"
                        },
                        new
                        {
                            IdConcelho = 287,
                            NomeConcelho = "Vila Nova de Poiares"
                        },
                        new
                        {
                            IdConcelho = 288,
                            NomeConcelho = "Vila Pouca de Aguiar"
                        },
                        new
                        {
                            IdConcelho = 289,
                            NomeConcelho = "Vila Real"
                        },
                        new
                        {
                            IdConcelho = 290,
                            NomeConcelho = "Vila Real de Santo António"
                        },
                        new
                        {
                            IdConcelho = 291,
                            NomeConcelho = "Vila Velha de Ródão"
                        },
                        new
                        {
                            IdConcelho = 292,
                            NomeConcelho = "Vila Verde"
                        },
                        new
                        {
                            IdConcelho = 293,
                            NomeConcelho = "Vila Viçosa"
                        },
                        new
                        {
                            IdConcelho = 294,
                            NomeConcelho = "Vila de Rei"
                        },
                        new
                        {
                            IdConcelho = 295,
                            NomeConcelho = "Vila do Bispo"
                        },
                        new
                        {
                            IdConcelho = 296,
                            NomeConcelho = "Vila do Conde"
                        },
                        new
                        {
                            IdConcelho = 297,
                            NomeConcelho = "Vila do Porto"
                        },
                        new
                        {
                            IdConcelho = 298,
                            NomeConcelho = "Vimioso"
                        },
                        new
                        {
                            IdConcelho = 299,
                            NomeConcelho = "Vinhais"
                        },
                        new
                        {
                            IdConcelho = 300,
                            NomeConcelho = "Viseu"
                        },
                        new
                        {
                            IdConcelho = 301,
                            NomeConcelho = "Vizela"
                        },
                        new
                        {
                            IdConcelho = 302,
                            NomeConcelho = "Vouzela"
                        },
                        new
                        {
                            IdConcelho = 303,
                            NomeConcelho = "Águeda"
                        },
                        new
                        {
                            IdConcelho = 304,
                            NomeConcelho = "Évora"
                        },
                        new
                        {
                            IdConcelho = 305,
                            NomeConcelho = "Ílhavo"
                        },
                        new
                        {
                            IdConcelho = 306,
                            NomeConcelho = "Óbidos"
                        });
                });

            modelBuilder.Entity("JobPortal_API.Models.CV", b =>
                {
                    b.Property<int>("IdCV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCV"), 1L, 1);

                    b.Property<string>("Competencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpProfissional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCandidatoCv")
                        .HasColumnType("int");

                    b.Property<int>("IdConcelho")
                        .HasColumnType("int");

                    b.Property<int>("IdEscolaridade")
                        .HasColumnType("int");

                    b.Property<string>("Interesses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCV");

                    b.HasIndex("IdCandidatoCv");

                    b.HasIndex("IdConcelho");

                    b.HasIndex("IdEscolaridade");

                    b.ToTable("CV");
                });

            modelBuilder.Entity("JobPortal_API.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdConcelho")
                        .HasColumnType("int");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoFuncionarios")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Telefone")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ZonaAtuacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("IdConcelho");

                    b.HasIndex("UserId");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("JobPortal_API.Models.Escolaridade", b =>
                {
                    b.Property<int>("IdEscolaridade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscolaridade"), 1L, 1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdEscolaridade");

                    b.ToTable("Escolaridade");

                    b.HasData(
                        new
                        {
                            IdEscolaridade = 1,
                            Tipo = "Ensino Básico"
                        },
                        new
                        {
                            IdEscolaridade = 2,
                            Tipo = "Ensino Secundário"
                        },
                        new
                        {
                            IdEscolaridade = 3,
                            Tipo = "Licenciatura"
                        },
                        new
                        {
                            IdEscolaridade = 4,
                            Tipo = "Mestrado"
                        },
                        new
                        {
                            IdEscolaridade = 5,
                            Tipo = "Doutoramento"
                        });
                });

            modelBuilder.Entity("JobPortal_API.Models.FileCV", b =>
                {
                    b.Property<int>("IdFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFile"), 1L, 1);

                    b.Property<int>("CandidatoIdCandidato")
                        .HasColumnType("int");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("IdCandidatoFile")
                        .HasColumnType("int");

                    b.HasKey("IdFile");

                    b.HasIndex("CandidatoIdCandidato");

                    b.ToTable("FileCV");
                });

            modelBuilder.Entity("JobPortal_API.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CandidatoIdCandidato")
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("IdCandidatoFoto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoIdCandidato");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("JobPortal_API.Models.LogoEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdEmpresaFoto")
                        .HasColumnType("int");

                    b.Property<byte[]>("Logo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("empresaIdEmpresa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("empresaIdEmpresa");

                    b.ToTable("LogoEmpresa");
                });

            modelBuilder.Entity("JobPortal_API.Models.OfertaEmprego", b =>
                {
                    b.Property<int>("IdOferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOferta"), 1L, 1);

                    b.Property<int>("Contagem")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaIdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdConcelho")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoContrato")
                        .HasColumnType("int");

                    b.Property<bool?>("IsFullTime")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPresencial")
                        .HasColumnType("bit");

                    b.Property<string>("Requisitos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Salario")
                        .HasColumnType("real");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("VagaDisponivel")
                        .HasColumnType("bit");

                    b.HasKey("IdOferta");

                    b.HasIndex("EmpresaIdEmpresa");

                    b.HasIndex("IdConcelho");

                    b.HasIndex("IdTipoContrato");

                    b.ToTable("OfertaEmprego");
                });

            modelBuilder.Entity("JobPortal_API.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReview"), 1L, 1);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReview");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("JobPortal_API.Models.TipoContrato", b =>
                {
                    b.Property<int>("IdTipoContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoContrato"), 1L, 1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoContrato");

                    b.ToTable("TipoContrato");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JobPortal_API.Models.AplicacaoTrabalho", b =>
                {
                    b.HasOne("JobPortal_API.Models.Candidato", "Candidato")
                        .WithMany("AplicacaoTrabalho")
                        .HasForeignKey("IdCandidato");

                    b.HasOne("JobPortal_API.Models.OfertaEmprego", "OfertaEmprego")
                        .WithMany("AplicacaoTrabalho")
                        .HasForeignKey("IdOferta");

                    b.Navigation("Candidato");

                    b.Navigation("OfertaEmprego");
                });

            modelBuilder.Entity("JobPortal_API.Models.Candidato", b =>
                {
                    b.HasOne("JobPortal_API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal_API.Models.CV", b =>
                {
                    b.HasOne("JobPortal_API.Models.Candidato", "IdCandidato")
                        .WithMany("CV")
                        .HasForeignKey("IdCandidatoCv");

                    b.HasOne("JobPortal_API.Models.Concelho", "Concelho")
                        .WithMany()
                        .HasForeignKey("IdConcelho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal_API.Models.Escolaridade", "Escolaridade")
                        .WithMany()
                        .HasForeignKey("IdEscolaridade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concelho");

                    b.Navigation("Escolaridade");

                    b.Navigation("IdCandidato");
                });

            modelBuilder.Entity("JobPortal_API.Models.Empresa", b =>
                {
                    b.HasOne("JobPortal_API.Models.Concelho", "Concelho")
                        .WithMany()
                        .HasForeignKey("IdConcelho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal_API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concelho");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal_API.Models.FileCV", b =>
                {
                    b.HasOne("JobPortal_API.Models.Candidato", "Candidato")
                        .WithMany("FileCV")
                        .HasForeignKey("CandidatoIdCandidato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("JobPortal_API.Models.Foto", b =>
                {
                    b.HasOne("JobPortal_API.Models.Candidato", "Candidato")
                        .WithMany("Foto")
                        .HasForeignKey("CandidatoIdCandidato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("JobPortal_API.Models.LogoEmpresa", b =>
                {
                    b.HasOne("JobPortal_API.Models.Empresa", "empresa")
                        .WithMany("LogoEmpresa")
                        .HasForeignKey("empresaIdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("empresa");
                });

            modelBuilder.Entity("JobPortal_API.Models.OfertaEmprego", b =>
                {
                    b.HasOne("JobPortal_API.Models.Empresa", "Empresa")
                        .WithMany("OfertaEmprego")
                        .HasForeignKey("EmpresaIdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal_API.Models.Concelho", "Concelho")
                        .WithMany()
                        .HasForeignKey("IdConcelho");

                    b.HasOne("JobPortal_API.Models.TipoContrato", "TipoContrato")
                        .WithMany()
                        .HasForeignKey("IdTipoContrato");

                    b.Navigation("Concelho");

                    b.Navigation("Empresa");

                    b.Navigation("TipoContrato");
                });

            modelBuilder.Entity("JobPortal_API.Models.Review", b =>
                {
                    b.HasOne("JobPortal_API.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JobPortal_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JobPortal_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JobPortal_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobPortal_API.Models.Candidato", b =>
                {
                    b.Navigation("AplicacaoTrabalho");

                    b.Navigation("CV");

                    b.Navigation("FileCV");

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("JobPortal_API.Models.Empresa", b =>
                {
                    b.Navigation("LogoEmpresa");

                    b.Navigation("OfertaEmprego");
                });

            modelBuilder.Entity("JobPortal_API.Models.OfertaEmprego", b =>
                {
                    b.Navigation("AplicacaoTrabalho");
                });
#pragma warning restore 612, 618
        }
    }
}
